<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;

class ProductCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @return array<int|string, mixed>
     */
    public function toArray(Request $request): array
    {
        // return parent::toArray($request);

        return [
            'data' => $this->collection,
            'extra_1' => 'Dado adicional no toArray'
        ];
    }
    public function with(Request $request)
    {
        // return parent::with($request); // TODO: Change the autogenerated stub
        return [
            'extra_information' => 'Another Data',
            'extra_2' => 'Dado adicional'
        ];
    }
}
